version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fiap-serverless-dev"
resolve_s3 = true
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "fiap-serverless-staging"
resolve_s3 = true
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging"

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "fiap-serverless-prod"
resolve_s3 = true
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
